name: Update Profile README with Dev Metrics

on:
  push:
    branches:
      - main  
  schedule:
    - cron: '0 0 * * *'  

jobs:
  update-dev-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "my-development-stats"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
